### ISSUE TITLE
Fatal error: Can't use function return value in write context validation error

### ISSUE THREAD

**Issue by darwintamban** [iGovPhil/gwt-drupal#1]
Fatal error: Can't use function return value in write context in C:\xampp\htdocs\website\sites\all\themes\gwt_drupal\template.php on line 618
im trying to use gwt-drupal 3.1.1!
how to fix this?

**Comment by v0j** [comment]
This issue was fixed on https://github.com/iGovPhil/gwt-drupal/commit/cfdf20c980b2290494b65e334736e8a9deb0d049

improved syntax handling for empty() function.

This issue will be added on the next release version.
