### ISSUE TITLE
Philippine Standard Time Block not working

### ISSUE THREAD

**Issue by mesl1012** [iGovPhil/gwt-drupal#11]
Philippine Standard Time Block not working.. I don't know why but it just displays the title

**Comment by v0j** [comment]
Which version are you currently using?

There is an upcoming new major update for the template. Can you download the new [version on master branch](https://github.com/iGovPhil/gwt-drupal/archive/master.zip) and test it out?

**Comment by mesl1012** [comment]
On firebug it says 
Error: Element not found! Element with ID of "pst-time"" was not found.
throw new Error('Element not found! Element with ID of "' + elementId + '"" was ...

gwtpst....0600634(line 183, col 15)

and drupal gives errors:

```
Notice: Undefined variable: links in gwt_drupal_links__system_main_menu_mobile() (line 56 of D:\WWW\pshs\sites\all\themes\gwt_drupal\template.php).
Warning: Invalid argument supplied for foreach() in _gwt_drupal_link_render() (line 157 of D:\WWW\pshs\sites\all\themes\gwt_drupal\template.php).
```

**Comment by mesl1012** [comment]
sorry forget about the firebug error.. its working now.. but the drupal error is still there.. i just forgot to overwrite the theme modules..

**Comment by v0j** [comment]
I have already patch the template.php to load the main-menu links to avoid the error.

can you test the new version in master?
simple patching would do.

Thanks,

**Comment by mesl1012** [comment]
Its cool now. thanks!

**Comment by v0j** [comment]
one last note: since master is still in development you will need to wait for the next stable release.
