### ISSUE TITLE
Large headings in some sidebars

### ISSUE THREAD

**Issue by darwintamban** [iGovPhil/gwt-drupal#2]
![error](https://cloud.githubusercontent.com/assets/6139278/7764618/78bdb40c-0086-11e5-8e61-ffb793cfd66b.png)

**Comment by v0j** [comment]
Which version of the template are you using?

**Comment by darwintamban** [comment]
gwt-drupal-3.4 po

**Comment by v0j** [comment]
we will be creating a patch for it.

**Comment by v0j** [comment]
This issue have been patch on version 3.4.1 https://github.com/iGovPhil/gwt-drupal/commit/1e75937a137df4f5e5263a600ff74b1a47738d7c
