### ISSUE TITLE
Appearance Settings Masthead font-color and font family option not working

### ISSUE THREAD

**Issue by svizcara** [iGovPhil/gwt-drupal#8]
Also, Sans-serif option not taking effect.
These are observed in gwt-drupal v2.0.4.
(Or are these issues specific to my environment?)

Thank you very much!

**Comment by v0j** [comment]
@svizcara apologies for delay of response, will look into it.

**Comment by v0j** [comment]
I have updated the master branch and soft released the gwt-drupal p2.0.5 which you may download here:
https://github.com/iGovPhil/gwt-drupal/archive/master.zip

let me know if you encounter other issues.

Thanks!

**Comment by svizcara** [comment]
Thank you! I have tried the soft release of the gwt-drupal and font-color already responds to the Appearance setting. Only the sans-serif option for the header and banner fonts is not yet observed.

I will let you know if I encounter other issues.

Again, thanks!

**Comment by v0j** [comment]
let me know if the Font Family selection option on the theme option of GWT-Drupal works so that I can close this issue queue.

Thanks

**Comment by svizcara** [comment]
Sorry, I have just read your comment. I have also taken upon myself to close the issue. I have reopened this issue to give a comment. The Font Family selection option works fine already! Thank you very much!

**Comment by v0j** [comment]
this issue is now closed.
