### ISSUE TITLE
Top Bar Search region spans a whole row at the top bar.

### ISSUE THREAD

**Issue by svizcara** [iGovPhil/gwt-drupal#9]
![screen shot 2016-05-12 at 7 33 14 am](https://cloud.githubusercontent.com/assets/13112661/15200109/83f715ea-1816-11e6-82a7-06e13f6f57db.png)

It also shows up in the top bar in mobile view:
![screen shot 2016-05-12 at 7 54 00 am](https://cloud.githubusercontent.com/assets/13112661/15200137/c832e446-1816-11e6-81b8-0f928ce3310f.png)

**Comment by v0j** [comment]
Thank you for reporting again.

it seems that the class for the search container doesn't append properly. Will check it out.

**Comment by v0j** [comment]
Please download and test the pre-release version **GWT-drupal P 2.0.6** here:
https://github.com/iGovPhil/gwt-drupal/archive/master.zip

then update your template and clear your cache.

let me know if this solves this issue, thanks!

**Comment by svizcara** [comment]
Thank you. I have tested the pre-release version GWT-drupal P 2.0.6 and the patch worked well!
I can now position the Search bar in the Top Bar Search region without it spanning a whole row:

![screen shot 2016-05-12 at 11 27 08 am](https://cloud.githubusercontent.com/assets/13112661/15203290/a9e3007a-1834-11e6-90aa-dae9aece7273.png)

It's also gone from the top bar for the mobile view:
![screen shot 2016-05-12 at 11 26 46 am](https://cloud.githubusercontent.com/assets/13112661/15203321/f8d5f3c2-1834-11e6-906c-9d7e142b6625.png)

Also, the sans-serif option already takes effect! Please note, however, that the logo name is not centered vertically if the agency slogan is not provided. 
![screen shot 2016-05-12 at 11 27 19 am](https://cloud.githubusercontent.com/assets/13112661/15203339/333af85a-1835-11e6-9c8c-eab449ff7f1d.png)

Thank you very much for fixing these issues! :-)

**Comment by v0j** [comment]
the agency logo name usually has 3 parts, Republic of the philipines text on top, site name/agency name in the middle and site slogan on the bottom in which if all the 3 parts have been filled it will be vertically aligned with the logo.

**Comment by svizcara** [comment]
Ok. I take it that means the agency slogan is required for the agency logo name?

**Comment by v0j** [comment]
not strictly required because there are some cases that slogan/sub text are not needed.
we need to support as many agencies as possible so we have to cater optional agency slogan.

**Comment by v0j** [comment]
If in case that what you are doing has no slogan and you needed to vertically align with the image logo, i would suggest to use the image logo with the site name/ agency name included on the image, then omit the text base site name and republic text. (via gwt-drupal appearance settings toggle)

**Comment by svizcara** [comment]
Ok. Thank you. I shall follow this advice regarding the agency logo name w/o slogan for now.
